{
 "title": "Network Telemetry",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "NE", "query": { "query": "label_values(source)" } },
   {
    "name": "Services",
    "query": {
     "query": "label_values(network_instance_name)"
    }
   },
   {
    "name": "Logs",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "DC Fabric", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "DC Fabric Throughput",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 13, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    { "expr": "interface_traffic_rate_in_bps", "legendFormat": "__auto" },
    {
     "expr": "interface_traffic_rate_out_bps",
     "legendFormat": "{{source}}:{{interface_name}}:OUT"
    }
   ]
  },
  {
   "title": "Network Telemetry",
   "type": "andrewbmchugh-flow-panel",
   "gridPos": { "h": 21, "w": 11, "x": 13, "y": 1 },
   "targets": [
    {
     "expr": "interface_oper_state",
     "legendFormat": "oper-state:{{source}}:{{interface_name}}"
    },
    {
     "expr": "interface_traffic_rate_out_bps",
     "legendFormat": "{{source}}:{{interface_name}}:out"
    },
    {
     "expr": "interface_traffic_rate_in_bps",
     "legendFormat": "{{source}}:{{interface_name}}:in"
    }
   ]
  },
  {
   "title": "Front panel view",
   "type": "andrewbmchugh-flow-panel",
   "gridPos": { "h": 16, "w": 13, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "interface_oper_state",
     "legendFormat": "oper-state:{{source}}:{{interface_name}}"
    }
   ]
  },
  { "title": "$NE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Routing Stats",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "network_instance_route_table_ipv4_unicast_statistics_active_routes{network_instance_name=\"default\",source=\"$NE\"}",
     "legendFormat": "IPv4 Active Routes"
    },
    {
     "expr": "network_instance_route_table_ipv4_unicast_statistics_total_routes{network_instance_name=\"default\",source=\"$NE\"}",
     "legendFormat": "IPv4 Total Routes"
    },
    {
     "expr": "network_instance_route_table_ipv4_unicast_statistics_active_routes_with_ecmp{network_instance_name=\"default\",source=\"$NE\"}",
     "legendFormat": "IPv4 Active ECMP Routes"
    }
   ]
  },
  {
   "title": "BGP Peer stats",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 7, "x": 5, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "network_instance_protocols_bgp_statistics_up_peers{network_instance_name=\"default\",source=\"$NE\"}",
     "legendFormat": "Up Peers"
    },
    {
     "expr": "network_instance_protocols_bgp_statistics_total_peers{network_instance_name=\"default\",source=\"$NE\"}",
     "legendFormat": "Total Peers"
    },
    {
     "expr": "network_instance_protocols_bgp_statistics_disabled_peers{network_instance_name=\"default\",source=\"$NE\"}",
     "legendFormat": "Disabled Peers"
    }
   ]
  },
  {
   "title": "Throughput ",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "interface_traffic_rate_in_bps{source=\"$NE\"}",
     "legendFormat": "{{interface_name}}:IN"
    },
    {
     "expr": "interface_traffic_rate_out_bps{source=\"$NE\"}",
     "legendFormat": "{{interface_name}}:OUT"
    }
   ]
  },
  {
   "title": "BGP Route Stats",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 7, "x": 5, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "network_instance_protocols_bgp_statistics_total_received_routes{network_instance_name=\"default\",source=\"$NE\"}",
     "legendFormat": "Total Received Routes"
    },
    {
     "expr": "network_instance_protocols_bgp_statistics_total_active_routes{network_instance_name=\"default\",source=\"$NE\"}",
     "legendFormat": "Total Active Routes"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "platform_control_cpu_total_instant{source=\"$NE\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "platform_control_memory_free{source=\"$NE\"}",
     "legendFormat": "Free "
    },
    {
     "expr": "platform_control_memory_utilization{source=\"$NE\"}",
     "legendFormat": "Utilization"
    },
    {
     "expr": "platform_control_memory_reserved{source=\"$NE\"}",
     "legendFormat": "Reserved"
    },
    {
     "expr": "platform_control_memory_physical{source=\"$NE\"}",
     "legendFormat": "Physical"
    }
   ]
  },
  {
   "title": "Service: $Services",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "network_instance_oper_state{network_instance_name='$Services'}",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "Running SR Linux applications",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 33 },
   "targets": [
    {
     "expr": "system_app_management_application_pid{source='$NE'}",
     "legendFormat": "{{application_name}}"
    }
   ]
  },
  { "title": "Logging $NE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Log: $Logs",
   "type": "logs",
   "gridPos": { "h": 13, "w": 15, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "{application=\"$Logs\", source=\"$NE\"}"
    }
   ]
  },
  {
   "title": "Total logs $NE",
   "type": "piechart",
   "gridPos": { "h": 21, "w": 9, "x": 15, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (application) (count_over_time({source=\"$NE\"}[$__range]))",
     "legendFormat": "{{application}}"
    }
   ]
  },
  {
   "title": "Log volume: $Logs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 55 },
   "targets": [
    {
     "expr": "sum by (level) (count_over_time({application=\"$Logs\",source=\"$NE\"} | logfmt [$__interval]))",
     "legendFormat": "{{level}}"
    }
   ]
  }
 ]
}