apiVersion: inv.sdcio.dev/v1alpha1
kind: TargetSyncProfile
metadata:
  name: gnmi-get
  namespace: default
spec:
  buffer: 0
  workers: 50
  validate: true
  sync:
  - name: config
    protocol: gnmi
    port: 57400
    paths:
      - /
    mode: get
    encoding: JSON_IETF
    interval: 2s
